"""Fix curriculum table schema

Revision ID: 009b2b8387a8
Revises: f1981c94c715
Create Date: 2025-03-23 11:19:19.884379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009b2b8387a8'
down_revision: Union[str, None] = 'f1981c94c715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curriculum', 'lecture_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'practice_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'exam_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'test_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'course_project_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'total_practice_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('qualifications', 'program_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('retrainings', 'program_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('teachers', 'education_level',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'education_level',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('retrainings', 'program_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('qualifications', 'program_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('curriculum', 'total_practice_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'course_project_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'test_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'exam_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'practice_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'lecture_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    # ### end Alembic commands ###
