"""на половину настроена БД для учебного плана

Revision ID: 1ab76ceff3cf
Revises: 8d551079543e
Create Date: 2025-03-23 22:01:12.327243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab76ceff3cf'
down_revision: Union[str, None] = '8d551079543e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum', sa.Column('semester', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum', 'semester')
    # ### end Alembic commands ###
