"""Добавлено поле year в таблицу education_programs

Revision ID: 435e23f3529c
Revises: e3a6d8e6cfaf
Create Date: 2025-03-25 20:34:06.419065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435e23f3529c'
down_revision: Union[str, None] = 'e3a6d8e6cfaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_programs', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education_programs', 'year')
    # ### end Alembic commands ###
