"""Fix curriculum table schema

Revision ID: 5ccd78ba54f8
Revises: 009b2b8387a8
Create Date: 2025-03-23 11:20:23.059945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccd78ba54f8'
down_revision: Union[str, None] = '009b2b8387a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curriculum', 'id', new_column_name='curriculum_id')
    op.drop_column('curriculum', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('curriculum', 'curriculum_id', new_column_name='id')
    op.drop_column('curriculum', 'curriculum_id')
    # ### end Alembic commands ###
