"""Новое поле в teachers

Revision ID: 7431ac931531
Revises: c163b20aa78f
Create Date: 2025-04-10 13:04:33.187527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7431ac931531'
down_revision: Union[str, None] = 'c163b20aa78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('disciplines_raw', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'disciplines_raw')
    # ### end Alembic commands ###
