"""initial

Revision ID: 862c6584c37f
Revises: 148e8e6dd25b
Create Date: 2025-04-02 01:32:33.192467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862c6584c37f'
down_revision: Union[str, None] = '148e8e6dd25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('education_programs_short_name_key', 'education_programs', type_='unique')
    op.create_index(op.f('ix_education_programs_short_name'), 'education_programs', ['short_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_education_programs_short_name'), table_name='education_programs')
    op.create_unique_constraint('education_programs_short_name_key', 'education_programs', ['short_name'])
    # ### end Alembic commands ###
