"""Обновил связи в БД

Revision ID: 97f1d3821398
Revises: 435e23f3529c
Create Date: 2025-03-25 22:31:10.247726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97f1d3821398'
down_revision: Union[str, None] = '435e23f3529c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taught_disciplines', sa.Column('curriculum_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'taught_disciplines', 'curriculum', ['curriculum_id'], ['curriculum_id'], ondelete='CASCADE')
    op.drop_column('taught_disciplines', 'discipline_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taught_disciplines', sa.Column('discipline_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'taught_disciplines', type_='foreignkey')
    op.drop_column('taught_disciplines', 'curriculum_id')
    # ### end Alembic commands ###
