"""Initial migration

Revision ID: d2c7d2edfb31
Revises: 9677fee7e358
Create Date: 2025-04-10 22:22:01.623295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2c7d2edfb31'
down_revision: Union[str, None] = '9677fee7e358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_programs',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('program_id'),
    sa.UniqueConstraint('program_name')
    )
    op.create_index(op.f('ix_education_programs_program_id'), 'education_programs', ['program_id'], unique=False)
    op.create_index(op.f('ix_education_programs_short_name'), 'education_programs', ['short_name'], unique=True)
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('education_level', sa.Text(), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('base_education_specialty', sa.String(length=255), nullable=True),
    sa.Column('scientific_education_specialty', sa.String(length=255), nullable=True),
    sa.Column('academic_degree', sa.String(length=255), nullable=True),
    sa.Column('academic_title', sa.String(length=255), nullable=True),
    sa.Column('total_experience', sa.Integer(), nullable=True),
    sa.Column('teaching_experience', sa.Integer(), nullable=True),
    sa.Column('professional_experience', sa.Integer(), nullable=True),
    sa.Column('disciplines_raw', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculum',
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('semester', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('lecture_hours', sa.Float(), nullable=True),
    sa.Column('practice_hours', sa.Float(), nullable=True),
    sa.Column('lab_hours', sa.Float(), nullable=True),
    sa.Column('exam_hours', sa.Float(), nullable=True),
    sa.Column('test_hours', sa.Float(), nullable=True),
    sa.Column('course_project_hours', sa.Float(), nullable=True),
    sa.Column('total_practice_hours', sa.Float(), nullable=True),
    sa.Column('final_work_hours', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['education_programs.program_id'], ),
    sa.PrimaryKeyConstraint('curriculum_id')
    )
    op.create_table('qualifications',
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('qualification_id')
    )
    op.create_index(op.f('ix_qualifications_qualification_id'), 'qualifications', ['qualification_id'], unique=False)
    op.create_table('retrainings',
    sa.Column('retraining_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('retraining_id')
    )
    op.create_index(op.f('ix_retrainings_retraining_id'), 'retrainings', ['retraining_id'], unique=False)
    op.create_table('teacher_programs',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['education_programs.program_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE')
    )
    op.create_table('taught_disciplines',
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('curriculum_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.curriculum_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('discipline_id')
    )
    op.create_index(op.f('ix_taught_disciplines_discipline_id'), 'taught_disciplines', ['discipline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taught_disciplines_discipline_id'), table_name='taught_disciplines')
    op.drop_table('taught_disciplines')
    op.drop_table('teacher_programs')
    op.drop_index(op.f('ix_retrainings_retraining_id'), table_name='retrainings')
    op.drop_table('retrainings')
    op.drop_index(op.f('ix_qualifications_qualification_id'), table_name='qualifications')
    op.drop_table('qualifications')
    op.drop_table('curriculum')
    op.drop_table('users')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_education_programs_short_name'), table_name='education_programs')
    op.drop_index(op.f('ix_education_programs_program_id'), table_name='education_programs')
    op.drop_table('education_programs')
    # ### end Alembic commands ###
