"""initial

Revision ID: da3f099f0449
Revises: d4a8bfd13239
Create Date: 2025-04-02 20:16:48.131012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3f099f0449'
down_revision: Union[str, None] = 'd4a8bfd13239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum', sa.Column('lab_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum', 'lab_hours')
    # ### end Alembic commands ###
