"""Обновление таблицы EducationProgram

Revision ID: e3a6d8e6cfaf
Revises: 52c451664bcf
Create Date: 2025-03-25 19:44:38.744197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a6d8e6cfaf'
down_revision: Union[str, None] = '52c451664bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education_programs', sa.Column('short_name', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'education_programs', ['short_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'education_programs', type_='unique')
    op.drop_column('education_programs', 'short_name')
    # ### end Alembic commands ###
