"""Add curriculum table

Revision ID: f1981c94c715
Revises: ce0ae5d918d8
Create Date: 2025-03-23 11:05:58.983828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1981c94c715'
down_revision: Union[str, None] = 'ce0ae5d918d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Переименовываем столбец id в curriculum_id
    op.alter_column('curriculum', 'id', new_column_name='curriculum_id')
    op.alter_column('curriculum', 'lecture_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'practice_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'exam_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'test_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'course_project_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('curriculum', 'total_practice_hours',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('curriculum', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем обратно (переименовываем curriculum_id в id)
    op.alter_column('curriculum', 'curriculum_id', new_column_name='id')
    op.alter_column('curriculum', 'total_practice_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'course_project_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'test_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'exam_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'practice_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('curriculum', 'lecture_hours',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('curriculum', 'сurriculum_id')
    # ### end Alembic commands ###
